version: "3.8"
services:

  postgres:
    image: library/postgres:12-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=quarkus_test
      - POSTGRES_PASSWORD=quarkus_test
      - POSTGRES_DB=quarkus_test
